name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pm2 stop hilop-website
            cd ~/hilop-website
            touch .env
            echo "${{ secrets.PROD_ENV }}" > .env
            git pull origin main
            npm install
            npm run build
            pm2 restart hilop-website
